window.RelationUI=(()=>{
  const NS=WorldUtils.svgNS;
  function active(item){return WorldMap.isActive(item,WorldState.currentYear)}
  function renderGraph(edgesId,nodesId,nodes,edges,onClick){
    const edgesBox=document.getElementById(edgesId),nodesBox=document.getElementById(nodesId);if(!edgesBox||!nodesBox)return;edgesBox.innerHTML='';nodesBox.innerHTML='';const nodeMap=Object.fromEntries(nodes.map(n=>[n.id,n]));
    edges.forEach(edge=>{const a=nodeMap[edge.from],b=nodeMap[edge.to];if(!a||!b)return;const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,ux=dx/len,uy=dy/len,x1=a.x+ux*16,y1=a.y+uy*16,x2=b.x-ux*16,y2=b.y-uy*16;const line=document.createElementNS(NS,'line');line.classList.add('rel-edge');if(WorldState.currentYear<edge.startYear)line.classList.add('future');if(edge.endYear&&WorldState.currentYear>edge.endYear)line.classList.add('rel-edge-ended');line.setAttribute('x1',x1);line.setAttribute('y1',y1);line.setAttribute('x2',x2);line.setAttribute('y2',y2);line.setAttribute('stroke',edge.color||'#4a5665');line.setAttribute('stroke-width','1.6');if(edge.dashed)line.setAttribute('stroke-dasharray','4 3');edgesBox.appendChild(line);const label=document.createElementNS(NS,'text');label.classList.add('rel-edge-label');label.setAttribute('x',(x1+x2)/2);label.setAttribute('y',(y1+y2)/2-3);label.textContent=edge.label;edgesBox.appendChild(label)});
    nodes.forEach(node=>{const future=WorldMap.isFuture(node,WorldState.currentYear),ended=WorldMap.isEnded(node,WorldState.currentYear);const g=document.createElementNS(NS,'g');g.classList.add('rel-node');if(future)g.classList.add('future');if(ended)g.classList.add('rel-node-ended');g.dataset.id=node.id;g.style.color=node.color;const halo=document.createElementNS(NS,'circle');halo.setAttribute('cx',node.x);halo.setAttribute('cy',node.y);halo.setAttribute('r',15);halo.setAttribute('fill',node.color);halo.setAttribute('opacity','.12');g.appendChild(halo);const dot=document.createElementNS(NS,'circle');dot.classList.add('dot');dot.setAttribute('cx',node.x);dot.setAttribute('cy',node.y);dot.setAttribute('r',8);dot.setAttribute('fill',node.color);dot.setAttribute('stroke','#0e1116');dot.setAttribute('stroke-width','2');g.appendChild(dot);const name=document.createElementNS(NS,'text');name.classList.add('rel-name');name.setAttribute('x',node.x);name.setAttribute('y',node.y+26);name.textContent=node.name;g.appendChild(name);const role=document.createElementNS(NS,'text');role.classList.add('rel-role');role.setAttribute('x',node.x);role.setAttribute('y',node.y+37);role.textContent=active(node)?node.role:(future?'尚未登场':'已离场');g.appendChild(role);g.addEventListener('click',e=>{e.stopPropagation();if(future){showToast(`“${node.name}”将在天启${WorldUtils.toCN(node.startYear)}年登场`);return;}document.querySelectorAll('.rel-node').forEach(x=>x.classList.remove('selected'));g.classList.add('selected');onClick(node);});nodesBox.appendChild(g)});
  }
  function renderAll(){renderGraph('factionEdges','factionNodes',window.WorldData.factions,window.WorldData.factionRelations,node=>WorldState.select('faction',node.id));renderGraph('relationEdges','relationNodes',window.WorldData.characters,window.WorldData.characterRelations,node=>WorldState.select('character',node.id));updateDescriptions()}
  function updateDescriptions(){const y=WorldState.currentYear;const activeF=window.WorldData.factions.filter(x=>WorldMap.isActive(x,y)).length;const activeC=window.WorldData.characters.filter(x=>WorldMap.isActive(x,y)).length;const activeFR=window.WorldData.factionRelations.filter(x=>WorldMap.isActive(x,y)).length;const activeCR=window.WorldData.characterRelations.filter(x=>WorldMap.isActive(x,y)).length;document.getElementById('factionPageDesc').textContent=`天启${WorldUtils.toCN(y)}年 · ${activeF}/${window.WorldData.factions.length} 个势力参与世界状态 · ${activeFR}/${window.WorldData.factionRelations.length} 条关系生效`;document.getElementById('relationPageDesc').textContent=`天启${WorldUtils.toCN(y)}年 · ${activeC}/${window.WorldData.characters.length} 位人物在场 · ${activeCR}/${window.WorldData.characterRelations.length} 条关系生效`;}
  function init(){renderAll();WorldState.on(reason=>{if(reason==='year'||reason==='selectionClear')renderAll();});}
  return {init,renderAll};
})();
